### ISSUE TITLE
persistent vs immutable terminology

### ISSUE THREAD

**Issue by glyn** [deadpixi/rope#2]
"Persistent" has connotations of being stored in stable storage.

E.g. consider this usage:
> // Ropes are persistent: there is no way to modify an existing rope.

The usual term would be "immutable", which doesn't carry unnecessary connotations.

**Comment by deadpixi** [comment]
Hopefully things should be more clear now.

**Comment by glyn** [comment]
Thanks @deadpixi. Unfortunately, you missed several occurrences of "persistent"/"persistence":

- [ ] in the repository "About" line
- [ ] in the repository contents: https://github.com/deadpixi/rope/search?q=persistent
- [ ] also: https://github.com/deadpixi/rope/search?q=persistence
